-- Retrieve all users' names and email addresses:
SELECT name, email FROM Users;

-- Retrieve all restaurants' names and addresses:
SELECT name, address FROM Restaurants;

-- Retrieve all menu items and their prices:
SELECT item_name, price FROM Menu;

-- Retrieve all orders with their total amounts:
SELECT order_id, order_total FROM Order_Table;

-- Retrieve all orders with their delivery status:
SELECT order_id, delivery_status FROM Order_Table;

-- Retrieve all orders assigned to delivery boys:
SELECT order_id, delivery_boy_id FROM Order_Assign;

-- Retrieve all ratings given by users:
SELECT user_id, delivery_boy_id, rating FROM Rating;

-- Retrieve all feedback from users:
SELECT user_id, delivery_boy_id, feedback FROM Feedback;

-- Retrieve all notifications for users:
SELECT user_id, message FROM Notifications;

-- Retrieve all admins' usernames and emails:
SELECT username, email FROM Admins;

-- Count the number of users in the database:
SELECT COUNT(user_id) AS total_users FROM Users;

-- Calculate the average rating given by users:
SELECT AVG(rating) AS average_rating FROM Rating;

-- Find the highest order total:
SELECT MAX(order_total) AS highest_order_total FROM Order_Table;

-- List all orders that are pending:
SELECT * FROM Order_Table WHERE delivery_status = 'Pending';

-- List all orders with a total amount greater than $30:
SELECT * FROM Order_Table WHERE order_total > 30.00;

-- Find the delivery boy who delivered the most orders:
SELECT delivery_boy_id, COUNT(*) AS total_orders_delivered
FROM Order_Assign
GROUP BY delivery_boy_id
ORDER BY total_orders_delivered DESC
LIMIT 1;

-- Find the most ordered menu item:
SELECT menu_id, COUNT(*) AS total_orders
FROM Order_Details
GROUP BY menu_id
ORDER BY total_orders DESC
LIMIT 1;

-- List all users who have placed more than 2 orders:
SELECT user_id, COUNT(*) AS total_orders_placed
FROM Order_Table
GROUP BY user_id
HAVING total_orders_placed > 2;

-- Calculate the total revenue generated by the restaurant:
SELECT SUM(order_total) AS total_revenue FROM Order_Table;

-- Find the delivery boy with the highest average rating:
SELECT delivery_boy_id, AVG(rating) AS average_rating
FROM Rating
GROUP BY delivery_boy_id
ORDER BY average_rating DESC
LIMIT 1;

-- List all orders along with their corresponding menu items:
SELECT ot.order_id, m.item_name
FROM Order_Details od
JOIN Order_Table ot ON od.order_id = ot.order_id
JOIN Menu m ON od.menu_id = m.menu_id;

-- Find the total number of items in the menu for each restaurant:
SELECT r.name AS restaurant_name, COUNT(m.menu_id) AS total_items
FROM Restaurants r
JOIN Menu m ON r.restaurant_id = m.restaurant_id
GROUP BY r.name;

-- List all orders with their payment method and status:
SELECT ot.order_id, p.payment_method, p.status
FROM Order_Table ot
JOIN Payment p ON ot.order_id = p.order_id;

-- Find the delivery boy who has delivered the most expensive order:
SELECT oa.delivery_boy_id, MAX(ot.order_total) AS max_order_total
FROM Order_Assign oa
JOIN Order_Table ot ON oa.order_id = ot.order_id
GROUP BY oa.delivery_boy_id
ORDER BY max_order_total DESC
LIMIT 1;

-- List all orders along with their assigned delivery boys and assigned time:
SELECT ot.order_id, db.name AS delivery_boy_name, oa.assigned_time
FROM Order_Table ot
JOIN Order_Assign oa ON ot.order_id = oa.order_id
JOIN Delivery_Boy db ON oa.delivery_boy_id = db.delivery_boy_id;

-- Calculate the total number of orders delivered:
SELECT COUNT(*) AS total_orders_delivered
FROM Order_Table
WHERE delivery_status = 'Delivered';

-- List all orders that were delivered and paid with a credit card:
SELECT *
FROM Order_Table ot
JOIN Payment p ON ot.order_id = p.order_id
WHERE ot.delivery_status = 'Delivered' AND p.payment_method = 'Credit Card';

-- Calculate the average price of menu items for each restaurant:
SELECT r.name AS restaurant_name, AVG(m.price) AS average_item_price
FROM Restaurants r
JOIN Menu m ON r.restaurant_id = m.restaurant_id
GROUP BY r.name;

-- List all orders along with the corresponding user's email and delivery status:
SELECT ot.order_id, u.email, ot.delivery_status
FROM Order_Table ot
JOIN Users u ON ot.user_id = u.user_id;

-- Find the delivery boy who delivered the most orders to a specific restaurant:
SELECT oa.delivery_boy_id, COUNT(*) AS total_orders_delivered
FROM Order_Assign oa
JOIN Order_Table ot ON oa.order_id = ot.order_id
WHERE ot.restaurant_id = 1 -- Replace 1 with the desired restaurant_id
GROUP BY oa.delivery_boy_id
ORDER BY total_orders_delivered DESC
LIMIT 1;
